name: 'Live'

trigger:
    branches:
        include:
            - main

pr: none

variables:
    - template: azure-pipelines.vars.yml

jobs:
    - template: azure-pipelines.common.yml
      parameters:
          message: 'Release $(Build.SourceVersion) $(Build.SourceVersionMessage)'
